vcs:
  type: git
agents:
  available:
  - copilot
  - claude
  - gemini
  - codex
  - antigravity
  selection:
    preferred_implementer: claude
    preferred_reviewer: codex
  auto_commit: true
project:
  uuid: 2c011d09-8272-470c-b9e2-e9ccf8ad3fbd
  slug: kg-automation
  node_id: 2af64e2d9c0e
  build_id: 44458b30-aad5-48c1-acd1-ff52274454fd
